fsl-dcu-drm-y := fsl_dcu_drm_drv.o \
	       fsl_dcu_drm_kms.o \
	       fsl_dcu_drm_connector.o \
	       fsl_dcu_drm_plane.o \
	       fsl_dcu_drm_crtc.o \
	       fsl_dcu_drm_fbdev.o \
	       fsl_dcu_drm_hdmicon.o
obj-$(CONFIG_DRM_FSL_DCU)	+= fsl-dcu-drm.o
